import Head from "next/head";
import { Button, Input, Col, Row, Space, Typography } from "antd";
import "antd/dist/antd.css";
import React, { useState, useEffect } from "react";

export default function BMI() {
  // useState
  const [Weight, setWeight] = useState(0);
  const [Height, setHeight] = useState(0);
  const [BMI, setBMI] = useState([]);
  const { Text } = Typography;
  function CBMI() {
    setBMI(Weight / ((Height * Height) / 10000));
  }
  // useEffect

  return (
    <div>
      <Head>
        <title>1moby</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <br></br>

        <div>
          <h1>Calculate</h1>
          <Row style={{ marginTop: 50 }}>
            <Col span={10}>
              <Input
                placeholder="Weight (Kg.) "
                color="red"
                size="large"
                type={"number"}
                onChange={(e) => {
                  setWeight(e.target.value);
                  return
                }}
              ></Input>
            </Col>

            <Col span={10}>
              <Input
                placeholder="Height (cm.)"
                size="large"
                type={"number"}
                onChange={(e) => {
                  setHeight(e.target.value);
                }}
              ></Input>
            </Col>
            <br></br>
          </Row>
          <br></br>
          <Col span={4}>
            <Button type="primary" onClick={() => CBMI(0)}>
              Calculate BMI me !
            </Button>
          </Col>
          <br></br>

          <div>
            <Space style={{ width: "100%" }}></Space>

            <Text keyboard className="RGB">
              {" "}
              BMI = {BMI}
            </Text>
          </div>
          <br></br>
          <Row className="RGB">
            <Col span={4}> น้ำหนักต่ำกว่าเกณฑ์ </Col>
            <Col span={8}> น้อยกว่า 18.5 ลงไป</Col>
            <Col span={6}> มีความเสี่ยงเกิดโรคขาดสารอาหาร </Col>
          </Row>
          <Row>
            <Col span={4}> น้ำหนักสมส่วน </Col>
            <Col span={8}>18.5 - 22.9</Col>
            <Col span={6}> โอกาสการเกิดโรคแทรกซ้อน น้อยที่สุด </Col>
          </Row>
          <Row>
            <Col span={4}> น้ำหนักเกินมาตรฐาน </Col>
            <Col span={8}>23.0 - 24.9</Col>
            <Col span={6}>
              {" "}
              ภาวะน้ำหนักเกินระยะเริ่มต้น เริ่มมีโรคแทรกซ้อนเล็กน้อย{" "}
            </Col>
          </Row>
          <Row>
            <Col span={4}> อ้วน </Col>
            <Col span={8}>25.0 - 29.9</Col>
            <Col span={6}>
              {" "}
              ภาวะน้ำหนักเกินมาก มีโรคแทรกซ้อนในระยะอ้วนเริ่มต้น{" "}
            </Col>
          </Row>
          <Row>
            <Col span={4}> อ้วนมาก </Col>
            <Col span={8}>มากกว่า 30.0 ขึ้นไป</Col>
            <Col span={6}>
              {" "}
              ภาวะน้ำหนักเกินมากที่สุดโอกาสการเกิดโรคแทรกซ้อนอย่าง โรคอ้วน
            </Col>
          </Row>
        </div>
      </main>
    </div>
  );
}
